### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by hoangt** [rv8-io/musl-riscv-toolchain#2]
1) Some URL links in "bootstrap.sh" script are not accessible thus I updated to get packages from GIT release page.

2) When I run "sudo bootstrap.sh riscv64", an error message appeared as below
configure: error: /bin/sh ../../src/binutils-2.28/config.sub -linux-musl failed
I used GCC-7.2, Ubuntu 14.04 (???)

Do you have any idea to resolve this issue?

Thanks
/T

**Comment by larkmjc** [comment]
The script doesn't need root privileges, however, the target directory `/opt/riscv/musl-riscv-toolchain` needs to be writable. I suggest running it as a normal user. Given you do not have a ./ in front of the script i'm assuming you have . in your path which is particularly dangerous when combined with root privileges.

From the error message, it looks like the ARCH variable is not being set for some reason. I'd have to see your modified script to figure out what is going on.

I'll look into bumping the dependencies or pointing them at the archives on the releases page...

**Comment by hoangt** [comment]
Hello michaeljclark,

I attached "my_bootstrap.sh". I also run this script "./my_boostrap.sh riscv64" without "sudo" by changing <bootstrap_prefix> to a writable location. I printed out <ARCH>, <LINUX_ARCH> and WITHARCH and they are set to correct values when running script. The error message is the same which I suspect that is due to "-march" option is not set correctly when running "configure".


[my_bootstrap.zip](https://github.com/rv8-io/musl-riscv-toolchain/files/1713054/my_bootstrap.zip)

**Comment by larkmjc** [comment]
Okay. I've figured out what's happening.

I'm making updates to the script because I had moved the riscv-linux repo. I also pointed a couple of the dependencies (mpc and mpfr) at the versions in https://gcc.gnu.org/pub/gcc/infrastructure/

RISC-V is now in mainline linux-4.15 which was released just a few days ago so I have changed the script to point the kernel.org upstream archive.

I've push changes to git. I'm just running a test build...

**Comment by larkmjc** [comment]
I've run a test build on Debian and it appears to be working.

Try checking out the latest version of the script and running the unmodified version.

```
sudo mkdir -p /opt/riscv
sudo chown $(id -u):$(id -g) /opt/riscv
./bootstrap.sh riscv64
```

**Comment by larkmjc** [comment]
It might be a good idea to remove the src and stamps directory before re-running the latest version of the script.

The only way you can end up with the string `-linux-musl` is if ${ARCH} is empty, as set here:

```
TRIPLE=${ARCH}-linux-musl${SUFFIX}
```

**Comment by hoangt** [comment]
Hi michaeljclark ,

New check-in worked perfectly. Thanks for your suggestions!
